version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: sales
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"  
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
      - ./html:/var/www/html  # Mount PHP files to Nginx container
    ports:
      - "80:80"  # Expose port 80 for web traffic
    depends_on:
      - php-fpm
    networks:
      - my_network

  php-fpm:
    build:
      context: .  # Specify the path to the directory containing the Dockerfile
    container_name: php-fpm
    volumes:
      - ./html:/var/www/html  # Mount PHP files to PHP-FPM container
    expose:
      - "9000"  # Expose PHP-FPM port to be used by Nginx
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge

